export const mockCourses = [
  {
    id: 'react-foundations',
    title: 'Modern React Foundations',
    category: 'React',
    level: 'Beginner',
    duration: '4h 20m',
    image: '/images/react.svg',
    description:
      'Build a clean React foundation with components, hooks, state management, and reusable patterns used across the company.',
    lessons: [
      { title: 'JSX, components, and props', duration: '25m' },
      { title: 'Hooks and local state', duration: '32m' },
      { title: 'Forms and reusable UI', duration: '28m' },
      { title: 'Project structure and patterns', duration: '35m' },
    ],
    progress: 35,
    enrolled: false,
    highlight: 'Front-end Enablement',
  },
  {
    id: 'dsa-masterclass',
    title: 'DSA Masterclass',
    category: 'DSA',
    level: 'Intermediate',
    duration: '6h 15m',
    image: '/images/dsa.svg',
    description:
      'Strengthen problem solving with arrays, recursion, trees, and practical interview-style scenarios.',
    lessons: [
      { title: 'Problem-solving workflow', duration: '22m' },
      { title: 'Arrays and hashing', duration: '40m' },
      { title: 'Stacks, queues, and linked lists', duration: '45m' },
      { title: 'Trees and traversal strategies', duration: '52m' },
    ],
    progress: 20,
    enrolled: false,
    highlight: 'Engineering Growth',
  },
  {
    id: 'devops-foundations',
    title: 'DevOps Foundations',
    category: 'DevOps',
    level: 'Intermediate',
    duration: '5h 10m',
    image: '/images/devops.svg',
    description:
      'Learn deployment pipelines, containers, observability, and delivery practices for internal teams.',
    lessons: [
      { title: 'CI/CD principles', duration: '30m' },
      { title: 'Docker and environment parity', duration: '44m' },
      { title: 'Monitoring and alerting', duration: '41m' },
      { title: 'Release management', duration: '33m' },
    ],
    progress: 50,
    enrolled: false,
    highlight: 'Platform Reliability',
  },
  {
    id: 'system-design-primer',
    title: 'System Design Primer',
    category: 'System Design',
    level: 'Advanced',
    duration: '7h 05m',
    image: '/images/system-design.svg',
    description:
      'Understand scalable architectures, trade-offs, caching, queues, and how to think like a staff engineer.',
    lessons: [
      { title: 'Capacity planning basics', duration: '35m' },
      { title: 'Caching and data partitioning', duration: '49m' },
      { title: 'Message queues and async flows', duration: '43m' },
      { title: 'Design review workshop', duration: '58m' },
    ],
    progress: 12,
    enrolled: false,
    highlight: 'Architecture',
  },
  {
    id: 'uiux-for-products',
    title: 'UI/UX for Product Teams',
    category: 'UI/UX',
    level: 'Beginner',
    duration: '3h 50m',
    image: '/images/uiux.svg',
    description:
      'Ship cleaner, more usable interfaces with design systems, spacing, hierarchy, and feedback patterns.',
    lessons: [
      { title: 'Foundations of visual hierarchy', duration: '24m' },
      { title: 'Spacing, color, and typography', duration: '31m' },
      { title: 'Component consistency', duration: '29m' },
      { title: 'Design review checklist', duration: '27m' },
    ],
    progress: 60,
    enrolled: false,
    highlight: 'Product Design',
  },
  {
    id: 'react-performance',
    title: 'React Performance Patterns',
    category: 'React',
    level: 'Advanced',
    duration: '4h 55m',
    image: '/images/react.svg',
    description:
      'Optimize render behavior, split components cleanly, and build fast React experiences for large teams.',
    lessons: [
      { title: 'Profiling and render cost', duration: '28m' },
      { title: 'State placement strategies', duration: '35m' },
      { title: 'Data fetching patterns', duration: '42m' },
      { title: 'Polishing performance hotspots', duration: '36m' },
    ],
    progress: 22,
    enrolled: false,
    highlight: 'Frontend Excellence',
  },
]